version: "3.8"

services:
  anti_proxy:
    image: nginx:1.18
    container_name: anti_proxy
    platform: linux/amd64
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./anti:/var/www/html
    ports:
      - 58081:80
    links:
      - anti_php-fpm

  anti_db:
    image: postgres:11
    container_name: anti_db
    platform: linux/amd64
    ports:
      - 65432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: anti
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  anti_php-fpm:
    build: docker/php-fpm
    container_name: anti_php-fpm
    platform: linux/amd64
    volumes:
      - ./docker/php-fpm/php.ini:/etc/php.ini
      - ./anti:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - anti_db

  anti_composer:
    container_name: anti_composer
    image: composer:2.0.12
    platform: linux/amd64
    volumes:
      - ./anti:/app
    entrypoint: composer

  anti_node:
    container_name: anti_node
    image: node:12.18.3
    platform: linux/amd64
    volumes:
      - ./anti:/var/www/html
    working_dir: /var/www/html
    entrypoint: yarn

volumes:
  postgres_data:
    driver: local